[versions]
# androidCoreDependencies
androidAppCompatVersion = "1.7.0"
androidxCoreVersion = "1.13.1"
androidLifecycleVersion = "2.8.6"

# kotlinDependencies
kotlinCore = "2.1.20"
coroutinesVersion = "1.10.2"
kotlinReflectVersion = "2.1.20"
kotlinSerializationVersion = "1.8.1"

# composeDependencies
composeActivity = "1.9.2"
composeVersion = "1.7.3"
composeNavigationVersion = "2.8.2"
composeMaterial3Version = "1.3.0"
composeMaterial2Version = "1.7.3"
composeConstraintLayout = "1.0.1"
composeLifecycleRuntimeVersion = "2.8.6"
composeRuntimeVersion = "1.7.3"

# composeCoil
coilVersion = "3.1.0"

# telephoto
telephotoVersion = "0.16.0"

# pagingDependencies
pagingVersion = "3.3.2"
pagingComposeVersion = "3.3.2"

# testDependencies
junitVersion = "4.13.2"
junitKtxVersion = "1.2.1"

# composePlaceholder
composePlaceholderVersion = "1.0.8"

# datastoreDependencies
datastoreVersion = "1.1.1"

# browserDependencies
browserVersion = "1.8.0"

# uCropDependencies
uCropVersion = '2.2.9'

# roomDependencies
roomVersion = "2.6.1"

# exoPlayerDependencies
media3Version = "1.4.1"

# androidXMediaDependencies
androidXMediaVersion = "1.7.0"

# kableDependencies
kableVersion = "0.29.1"

# networkDependencies
retrofitVersion = "2.11.0"
okHttpVersion = "4.12.0"

# firebaseDependencies
firebaseBomVersion = "33.4.0"

# billingDependencies
billingVersion = "7.1.1"

# libs.composeAccompanist
accompanistVersion = "0.36.0"

# ktlint dependencies
ktlintCoreVersion = "0.48.1"
ktlintVersion = "1.3.1"

# pdfDependencies
pdfMultipagingVersion = "7.1.15"
kotlinxHtmlVersion = "0.9.1"

# aspectj
aspectjweaverVersion = "1.9.22.1"

# bottomSheet
bottomSheetVersion = "1.33.0"

# plugins
# dependencies
androidApplicationPluginVersion = "8.4.2"
androidLibraryPluginVersion = "8.4.2"
kotlinAndroidPluginVersion = "2.1.20"
kotlinJvmPluginVersion = "2.1.20"
kotlinSerializationPluginVersion = "2.1.20"
ktlintPluginVersion = "12.1.0"
metalava = "0.3.5"
mavenPublish = "0.28.0"
paparazziPluginVersion = "1.3.5"
firebasePerfPluginVersion = "1.4.2"
aspectPluginVersion = "1.4.1"
junit = "1.2.1"
espressoCoreVersion = "3.6.1"
materialVersion = "1.12.0"

[libraries]
androidCoreDependencies-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
androidCoreDependencies-core = { module = "androidx.core:core-ktx", version.ref = "androidxCoreVersion" }
androidCoreDependencies-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidLifecycleVersion" }

aspectjweaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectjweaverVersion" }

bottomSheet = { module = "com.composables:core",  version.ref = "bottomSheetVersion" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflectVersion" }
kotlinDependencies-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinCore" }
kotlinDependencies-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinDependencies-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerializationVersion" }

composeDependencies-composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeDependencies-composeUi = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
composeDependencies-composePreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeVersion" }
composeDependencies-composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3Version" }
composeDependencies-composeMaterial2 = { module = "androidx.compose.material:material", version.ref = "composeMaterial2Version" }
composeDependencies-composeNavigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigationVersion" }
composeDependencies-composeConstraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout" }
composeDependencies-composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
composeDependencies-composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }
composeDependencies-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "composeLifecycleRuntimeVersion" }
composeDependencies-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeRuntimeVersion" }

composeCoil-core = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilVersion" }
composeCoil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilVersion" }
composeCoil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilVersion" }
telephoto-core = { module = "me.saket.telephoto:zoomable-image-coil3", version.ref = "telephotoVersion" }

ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlintCoreVersion" }
ktlint-ruleset = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlintVersion" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlintVersion" }

prf-multipaging = { module = "com.itextpdf:itext7-core", version.ref = "pdfMultipagingVersion" }
kotlinDependencies-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinxHtmlVersion" }

billingDependencies-billing = { module = "com.android.billingclient:billing", version.ref = "billingVersion" }
billingDependencies-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingVersion" }

pagingDependencies-core = { module = "androidx.paging:paging-runtime", version.ref = "pagingVersion" }
pagingDependencies-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingComposeVersion" }

testDependencies-junit = { module = "junit:junit", version.ref = "junitVersion" }
testDependencies-junitExt = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtxVersion" }
testDependencies-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }

composePlaceholder-core = { module = "com.eygraber:compose-placeholder", version.ref = "composePlaceholderVersion" }

datastoreDependencies-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastoreVersion" }
datastoreDependencies-datastoreCore = { module = "androidx.datastore:datastore-core", version.ref = "datastoreVersion" }

browserDependencies-core = { module = "androidx.browser:browser", version.ref = "browserVersion" }

ucropDependencies-core = { module = "com.github.yalantis:ucrop", version.ref = "uCropVersion" }

roomDependencies-room = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
roomDependencies-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
roomDependencies-kapt = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
roomDependencies-testing = { module = "androidx.room:room-testing", version.ref = "roomVersion" }
roomDependencies-paging = { module = "androidx.room:room-paging", version.ref = "roomVersion" }

media3Dependencies-core = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Version" }
media3Dependencies-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Version" }
media3Dependencies-session = { module = "androidx.media3:media3-session", version.ref = "media3Version" }

androidXMediaDependencies-core = { module = "androidx.media:media", version.ref = "androidXMediaVersion" }

kableDependencies-core = { module = "com.juul.kable:core", version.ref = "kableVersion" }

networkDependencies-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
networkDependencies-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttpVersion" }
networkDependencies-okHttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttpVersion" }
networkDependencies-kotlinSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofitVersion" }

firebaseDependencies-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebaseDependencies-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebaseDependencies-remoteconfig = { module = "com.google.firebase:firebase-config" }
firebaseDependencies-performance = { module = "com.google.firebase:firebase-perf" }

composeAccompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanistVersion" }

paparazi-core = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazziPluginVersion"}
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
android-library = { id = "com.android.library", version.ref = "androidLibraryPluginVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPluginVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinAndroidPluginVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvmPluginVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPluginVersion" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPluginVersion" }
metalava = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalava" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
firebase-performance = { id = "com.google.firebase:perf-plugin", version.ref = "firebasePerfPluginVersion" }
aspect = { id = "com.ibotta:plugin", version.ref = "aspectPluginVersion" }